### ISSUE TITLE
Performance Guide

### ISSUE THREAD

**Issue by mattcary** [google/gvisor-website#101] opened 2019-08-13 16:42 UTC
Hi,

In the performance guide page, the graphs aren't showing up for me. I just get raw text like

{{< graph id=“sysbench-memory” url=“/performance/sysbench-memory.csv” title=“perf.py sysbench.memory –runtime=runc –runtime=runsc” >}}

instead of the embedding graph which should presumably be displayed instead.

Thanks

Matt

**Comment by prattmic** [comment] 2019-08-13 17:52
Duplicate of #99

**Closed by prattmic** 2019-08-13 17:52 UTC
